
version: '3'
services:
  solr_nginx:
   image: nginx:latest
   container_name: solr_nginx
   volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/error.log:/etc/nginx/error_log.log
    - ./nginx/cache/:/etc/nginx/cache
   depends_on:
     - solr1
     - solr2
     - solr3
   ports:
   - 80:80
   networks:
   - solr

  solr1:
    image: solr:8.7
    container_name: solr1
    hostname: solr1
    ports:
     - "8981:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - SOLR_HEAP=2018m
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    volumes:
     - solr1data:/var/solr
     - ../libs/:/mycores/juris/libs:rw

  solr2:
    image: solr:8.7
    container_name: solr2
    hostname: solr2
    ports:
     - "8982:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - SOLR_HEAP=2018m
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    volumes:
     - solr2data:/var/solr
     - ../libs/:/mycores/juris/libs:rw

  solr3:
    image: solr:8.7
    container_name: solr3
    hostname: solr3
    ports:
     - "8983:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - SOLR_HEAP=2018m
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    volumes:
     - solr3data:/var/solr
     - ../libs/:/mycores/juris/libs:rw

  create-collection:
    image: solr:8.7
    container_name: create-collection
    environment:
      - SOLR_HOST=solr1
    networks:
      - solr
    volumes:
      - ../juris/conf:/mycores/juris/:rw
    command:
      - bash
      - "-e"
      - "-x"
      - "-c"
      - "wait-for-solr.sh --max-attempts 10 --wait-seconds 5 --solr-url http://$$SOLR_HOST:8983/; solr create_collection -c juris -d /mycores/juris -shards 3 -replicationFactor 1 -p 8983"

  zoo1:
    image: zookeeper:3.6
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      JVMFLAGS: "-Xmx1024m"
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      - solr
    volumes:
     - zoo1data:/data
     - zoo1datalog:/datalog

  zoo2:
    image: zookeeper:3.6
    container_name: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      JVMFLAGS: "-Xmx1024m"
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      - solr
    volumes:
     - zoo2data:/data
     - zoo2datalog:/datalog

  zoo3:
    image: zookeeper:3.6
    container_name: zoo3
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      JVMFLAGS: "-Xmx1024m"
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    networks:
      - solr
    volumes:
     - zoo3data:/data
     - zoo3datalog:/datalog

networks:
  solr:

volumes:
  solr1data:
  solr2data:
  solr3data:
  zoo1data:
  zoo1datalog:
  zoo2data:
  zoo2datalog:
  zoo3data:
  zoo3datalog:


