version: '3'
services:
  solr:
   container_name: core_juris  
   build:
      context: ./
      dockerfile: ./build/Dockerfile  
   ports:
    - "8983:8983"
   networks:
    - app-network
   volumes:
    - ./core/juris/:/mycores/juris:rw
    - ./libs/:/mycores/juris/libs:rw
    - data:/var/solr/
   environment:
   - SOLR_HEAP=1024m
   command:
    - solr-precreate
    - juris
    - /mycores/juris

networks:
  app-network:
    driver: bridge
volumes:
   data: