FROM solr:8.7


#RUN git config --global http.sslverify false

#RUN apt-get update -y
#RUN su root mkdir -p /mycores
#RUN chown -R solr:solr /mycores
#RUN chmod -R 777 /opt/solr/server/solr/mycores



